classDiagram
%% =======================
%% Paquetes / namespaces
%% =======================
namespace expresso.cli {
  class Expressor {
    +main(String[] args) void
  }
}

namespace expresso.transpiler {
  class Transpiler {
    +transpile(String expressoFile) void
  }
}

namespace expresso.compiler {
  class JavaBuild {
    +build(String expressoFile) void
  }
}

namespace expresso.runtime {
  class Runner {
    +run(String expressoFile) void
  }
}

%% =======================
%% Relaciones internas
%% =======================
Expressor ..> Transpiler : usa
Expressor ..> JavaBuild  : usa
Expressor ..> Runner     : orquesta

JavaBuild ..> Transpiler : invoca
Runner    ..> JavaBuild  : invoca

%% =======================
%% Dependencias externas (JDK)
%% =======================
class JavaCompiler
class ToolProvider
class ProcessBuilder
class Files
class Path

