classDiagram
%% =======================
%% Paquetes / namespaces
%% =======================

namespace expresso{
  class Expressor {
    +main(String[] args) void
  }
}

namespace expresso.Cli {
  class Cli {
    +cli(... "options") void
    +loadFile(String fileName) bool
    +transpileCommand(File f) void
    +buildCommand(File f) void
    +runCommand(File f) void
  }
}


namespace expresso.Transpiler {
  class Transpiler {
    +transpile(String expressoFile) void
    +write(File f) void
  }
}

namespace expresso.Builder {
  class Builder {
    +build(File f) bool
    +write(File f) bool
  }
}

namespace expresso.Runtime {
  class Runner {
    +run(String expressoFile) void
    +display(String expressoFile) void
  }
}

%% =======================
%% Relaciones internas
%% =======================
Expressor ..> Cli : usa
Cli ..> Transpiler : usa
Cli ..> Builder  : usa
Cli ..> Runner     : orquesta

Builder ..> Transpiler : invoca
Runner    ..> Builder  : invoca


