name: Build JAR and package .deb

on:
  push:
    branches: [ main ]
  pull_request:

env:
  APP_NAME: Expresso
  MAIN_CLASS: com.diezam04.expresso.Cli  # <- change if your main class differs

jobs:
  build-and-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Pick main JAR (prefer *-runner.jar)
        id: pick
        shell: bash
        run: |
          set -e
          jar=$(ls -1 target/*-runner.jar 2>/dev/null || true)
          if [ -z "$jar" ]; then jar=$(ls -1 target/*.jar | head -n1); fi
          echo "jar=$jar" >> "$GITHUB_OUTPUT"

      - name: jpackage -> .deb (minimal)
        run: |
          mkdir -p dist
          jpackage \
            --type deb \
            --name "${APP_NAME}" \
            --input target \
            --main-jar "$(basename '${{ steps.pick.outputs.jar }}')" \
            --main-class "${MAIN_CLASS}" \
            --dest dist

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: dist/*.deb
